name: Compile and Sync Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  process-and-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 python-dotenv zoneinfo

      - name: Run compiler
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python compiler.py

      - name: Run today_list
        run: python today_list.py

      - name: Run results
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python results.py

      - name: Run sync
        run: python sync.py

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Send email with results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Daily Betting Analysis - ${{ env.date }}
          body: Please find attached the betting analysis report for ${{ env.date }}
          attachments: ./synced_results_${{ env.date }}.csv
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: GitHub Actions
