name: Compile and Sync Workflow

on:

  workflow_dispatch:

  schedule:
    - cron: '0 1 * * *'

jobs:
  process-and-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any requirements

      - name: Run compiler
        run: python compiler.py

      - name: Run today_list
        run: python today_list.py

      - name: Run results
        run: python results.py

      - name: Run sync
        run: python sync.py

      - name: Send email with results
        uses: dawidd6/action-send-mail@v3
        env:
          MAIL_SERVER: ${{secrets.MAIL_SERVER}}
          MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
          MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
        with:
          server_address: ${{env.MAIL_SERVER}}
          server_port: 587
          username: ${{env.MAIL_USERNAME}}
          password: ${{env.MAIL_PASSWORD}}
          subject: Sync Results Output
          body: file://synced_results_$(date +'%Y%m%d').csv
          to: your-email@example.com
          from: GitHub Actions 