name: Save Odds Data

on:
  schedule:
    - cron: '0 4 * * *'  # Run save_odds at 11pm EST (4:00 UTC)
  workflow_dispatch:

jobs:
  save-odds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas tzdata python-dotenv

      - name: Run save_odds
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python scripts/save_odds.py

      - name: Commit and push odds data
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git stash -u  # Stash all changes, including untracked files
          git pull --rebase
          git stash pop  # Restore changes
          git add data/
          git commit -m "Update odds data" || exit 0
          git push
