name: Test Results and Sync

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-results-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas tzdata python-dotenv

      - name: Get yesterday's date
        id: date
        run: |
          date -d "yesterday" +'%Y%m%d' > date.txt
          echo "date=$(cat date.txt)" >> $GITHUB_ENV
          echo "Using date: $(cat date.txt)"

      - name: Run results
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python scripts/results.py

      - name: Run sync
        run: python scripts/sync.py

      - name: Send email with results
        uses: dawidd6/action-send-mail@v3
        env:
          MAIL_SERVER: ${{secrets.MAIL_SERVER}}
          MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
          MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
        with:
          server_address: ${{env.MAIL_SERVER}}
          server_port: 587
          username: ${{env.MAIL_USERNAME}}
          password: ${{env.MAIL_PASSWORD}}
          subject: Daily Betting Analysis - ${{ env.date }}
          body: Please find attached the betting analysis report for ${{ env.date }}
          attachments: ./data/sportsbook_performance_${{ env.date }}.csv
          to: ${{secrets.RECIPIENT_EMAIL}}, ${{secrets.RECIPIENT_EMAIL_2}}, ${{secrets.RECIPIENT_EMAIL_3}}
          from: GitHub Actions

      - name: Commit and push results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git stash -u
          git pull --rebase
          git stash pop
          git add data/
          git commit -m "Update results and sync data for ${{ env.date }}" || exit 0
          git push 